### ISSUE TITLE
Add Seed Server URL as Label to User Clusters

### ISSUE THREAD

**Issue by Courtlane** [svalabs/kubermatic-argocd-bridge#19]
## Description

**What:**
I would like to request the addition of the seed server URL as a label to user clusters.

**Why:**
Adding the seed server URL as a label/annotation to user clusters will allow for more flexible templating in ArgoCD ApplicationSets. This enhancement will enable ApplicationSets to loop through user clusters and use their values in templates (e.g., deploy apps to user cluster namespaces on seeds), but use the seed server as the destination and not the user cluster itself.

**How:**
- Add a label to user clusters that includes the seed server URL.

**Benefits:**
- Enhanced ability to manage and deploy applications across multiple usercluster namespaces on the seed server.

**Example:**
```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-applicationset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=zero"]
  generators:
    - clusters:
        selector:
          matchLabels:
            "clusterType": "usercluster"
        values:
          clusterUrl: '{{.metadata.annotations.seedUrl}}'
          clusterID: '{{.metadata.labels.clusterID}}'
  template:
    metadata:
      name: '{{.nameNormalized}}-authz-webhook'
    spec:
      project: default
      sources:
        - repoURL: <repo_url>
          targetRevision: feat/opa
          path: '<path>'
      destination:
        server: '{{.values.clusterUrl}}'
        namespace: 'cluster-{{.values.clusterID}}'
```
